### ISSUE TITLE
Creating initial liquidity orders as part of the market create process doesn't work 

### ISSUE THREAD

**Issue by CheckRazor** [AugurProject/augur-app#104]
I have successfully create binary markets and each time tried to add initial liquidity orders.  The market creation transaction works fine, but the initial liquidity orders are never created as defined in Augur-App.   Once market is created you can add liquidity order manually,  Setup - Augur-App - local node with metamask.

**Comment by garethtdavies** [comment]
I also experienced this setting up my first market. The market was created but not the initial liquidity orders as I detailed in the setup phase.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13770/github-creating-initial-liquidity-doesn-t-work

**Comment by JohnDanz** [comment]
@CheckRazor are you still having this issue after updating to the latest version of augur-app? Please let me know as I am not seeing this behavior on test networks. The latest version as of this writing is v1.0.3. https://github.com/AugurProject/augur-app/releases

**Comment by CheckRazor** [comment]
@JohnDanz I tested this issue using v 1.0.4 with local geth and metamask to create a binary market with initial liquidity on mainnet.  I submitted the market and after roughly 5 minutes in pending status I notice geth output say Error "Demoting invalidated transactions" .  It seems because the initial market transaction wasn't validated in a certain amount of time the additional liquidity transactions were demoted by geth.  I then raised the gas price on the market creation transaction in metamask and it was quickly accepted by mainnet but Augur App 1.0.4 hard crashed.  After relauching Augur App no liquidity transactions remained.

**Comment by JohnDanz** [comment]
@CheckRazor Sounds like the first issue was a geth/connection issue, not really an augur specific issue. I say this because when you raised gas price and tried again it worked fine, (outside that crash of augur-app... which could be a syncing issue). No liquidity transactions makes perfect sense to me, i wouldn't expect them to start prompting you on a crash. They are stored in memory until they are encoded and passed to your signing device/metamask and they aren't stored anywhere in a hard sense until they have been sent out as transactions and succeed (when the log is emitted from the contracts augur-node will store that information then it's persistent). So if the whole app crashed or you even just refreshed the page before signing your liquidity transactions i would expect them to never prompt you as they have been effectively wiped from memory. Obviously this doesn't cost you anything since you never sent them, but it can cause some confusion/frustration. We are looking into ways of improving market liquidity and maybe even adding a whole new section where you can add liquidity.

**Comment by joeykrug** [comment]
A bunch of other people have been reporting this issue too

**Comment by sharkcrayon** [comment]
@JohnDanz But @CheckRazor said "I then raised the gas price on the market creation transaction in metamask and it was quickly accepted by mainnet". That makes it sound like they signed the transactions before Augur App crashed.

@CheckRazor Is that right?

**Comment by adrake33** [comment]
@CheckRazor It sounds like you raised the gas price on the market creation transaction, but did you sign any of the liquidity transactions after that? Also, are you currently seeing this issue with Augur App [version 1.0.5](https://github.com/AugurProject/augur-app/releases/tag/v1.0.5)?

If so, can you please create a [Gist](https://gist.github.com/) with the log info (https://github.com/AugurProject/augur-app#logging) so we can get more info as to what might be causing the crash?

**Comment by CheckRazor** [comment]
The liquidity transactions were not signed as they didn't show up in
metamask to be signed while waiting for the market creation transaction to
go through.

Sorry, I have not had a chance to test in 1.0.5 (or 1.0.6) current
traveling in South America.  I will test the latest version next week when
I get back to my geth node and update this issue.

**Comment by sharkcrayon** [comment]
@CheckRazor We're working on a UI fix for this. Currently, we don't retain any record of what initial liquidity txs are queued up, so if your browser refreshes in the middle of the signing process you will not be reprompted to sign the ones you hadn't gotten to yet (as you noticed ;) ).

I'll let you know when we've pushed the fix.

**Comment by adrake33** [comment]
Closing this for now, as https://app.clubhouse.io/augur/story/14763/show-unsigned-initial-liquidity-orders-on-portfolio-my-markets-page is marked as Completed.
