### ISSUE TITLE
Server error while syncing on 1.04 - happening frequently

### ISSUE THREAD

**Issue by negamax** [AugurProject/augur-app#202]
Can't seem to make it work
<img width="912" alt="screen shot 2018-07-19 at 14 41 29" src="https://user-images.githubusercontent.com/1029486/42943071-19dee338-8b62-11e8-92f2-4acf481a0342.png">

**Comment by pimato** [comment]
same problem here: 

<img width="902" alt="screen shot 2018-07-19 at 4 18 46 pm" src="https://user-images.githubusercontent.com/5337809/42948284-725203a8-8b6f-11e8-88e7-907cb50ef6e9.png">

**Comment by gggh000** [comment]
Got the same error.

**Comment by Anastik** [comment]
Yeah, I've had this issue too. Your best bet is to close everything out and re-sync. I'd also recommend using [`augur.casino`](augur.casino) to do your trading and interact with the UI. It's a little less secure because it isn't your own node, but as long as you're running Metamask you should be good to go. Let me knmow if that works.

**Comment by Bomper** [comment]
> Your best bet is to close everything out and re-sync. 

I've found that you can just click "Switch network" and syncing will resume. No need to restart the app.

**Comment by petervecchiarelli** [comment]
Duplicate with #204 Please track progress there.
