### ISSUE TITLE
Scalar Market - Units Missing

### ISSUE THREAD

**Issue by page1** [AugurProject/augur-app#206]
When browsing markets the scalar markets show the units on the price bar.
<img width="1092" alt="screen shot 2018-07-19 at 12 43 41 pm" src="https://user-images.githubusercontent.com/6609556/42963410-66815ca4-8b51-11e8-8bcb-e1e0b155467a.png">

However when you click to view the market the units are not present on the market depth, orderbook, or outcomes tab and are not listed anywhere on the page.
<img width="1199" alt="screen shot 2018-07-19 at 12 44 28 pm" src="https://user-images.githubusercontent.com/6609556/42963463-85bb3ef0-8b51-11e8-85a8-4ba725a4820c.png">

Units will be important to understand at all points in the betting process from betting, to resolution/dispute.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14288/github-scalar-market-units-missing

**Comment by sharkcrayon** [comment]
@page1 I've added that to our roadmap and it's high on our priority list. Thanks for all of the feedback btw!

**Comment by page1** [comment]
np. This kind of platform has a lot of appeal to my analytics background.

**Comment by sharkcrayon** [comment]
@page1 We've added additional market details to Trading page. You'll now see scalar min, max, and denomination.

I think the other change we need to make here is to force the market creator to add a denomination. It's currently not required. 
Adding to issue tracker: https://app.clubhouse.io/augur/story/14882/make-the-denomination-field-required-for-scalar-markets

Your other the point that the midpoint should be shown in the denomination rather than ETH is an interesting one. On the one hand I feel like changing the midpoint to the denomination would help clarify how to trade on a scalar market (it would clarify the link between the limit price and the market's units), but on the other hand I feel like it might confuse things things because the trading takes place in ETH.

**Comment by adrake33** [comment]
@sharkcrayon Can this issue be closed now that https://app.clubhouse.io/augur/story/14882/make-the-denomination-field-required-for-scalar-markets is marked as Completed?
