### ISSUE TITLE
Market missing even though confirmed on Blockchain

### ISSUE THREAD

**Issue by negamax** [AugurProject/augur-app#78]
Another one after that is visible but it seem to be lost. Can give more details in PM

**Comment by TacoByte** [comment]
HOW TO FIX: delete the local augurnode sync data. (on OS X, it's Library/Application Support/augur). Relaunch Augur and let it resync from scratch. Now all the markets will show up correctly.

**Comment by negamax** [comment]
@TacoByte this worked.. still would be good to see this fixed at high priority

**Comment by garethtdavies** [comment]
Same issue and just to clarify above for others the directory is `~/Library/Application Support/augur` and I had to delete the `augur-1.db` file. On doing this it also fixed up the issue in #99.

**Comment by epheph** [comment]
@pgebheim @nuevoalex  and I have been working on this specific issue and we believe we understand the root cause. What follows is a technical explanation of what is going on, for future reference.

When a new block comes in, say, block X, we turn around and request, in another request, `eth_getLogs({fromBlock: X, toBlock: X, filter: $setOfContractsFilter})` in order to fetch the new data. Sometimes, there are no logs, and the JSONRPC result is:
```result: []```
Sometimes the result is populated with an array of logs.
```result: [{"topics":["0xddf25...}, {"topics":["0xddf25...}]```
Both are successful responses from getLogs.

When using infura (or ANY pool of load-balanced ethereum rpc nodes), which is backed by many geth nodes, requests are often served by nodes of slightly different sync state. Sometimes, we get a notification of a new block from a node (that is slightly ahead), then turn around and issue a `getLogs` request for that new block that gets routed to a different node (that is slightly behind) and has not seen that block.

Here is the problem: The ethereum protocol, as it relates to `eth_getLogs`. When we issue a getLogs for block `X`, to a node that has only ever seen highest block `X - 1`, the response to the getLogs request is:
```result: []```
Which is the EXACT same response we would have gotten if the node was aware of that block, but it had no logs in it. This is a bad interface for the ethereum protocol. If we received something back like
```result: null```
we could issue a retry, but without that, we cannot distinguish between hitting a node that is not aware of that block from hitting a node that IS aware of that block, but that block contains no logs.

Additionally, there is [EIP-234](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-234.md), which changes the format to this getLogs request to specify by blockHash, but it is not clear if the absence of that block will change the respond?

**Comment by epheph** [comment]
There are only two solutions to this problem (unless the protocol gets updated, I'll talk with @MicahZoltu about the best way to approach that).

1.) Run a [singular] ethereum-node, that is internally consistent between RPC calls
2.) "Lag" our sync by some quantity of blocks that would give a large pool of nodes a chance to propagate a block to all nodes before we request more information from the pool.

We are currently implementing 2 . This will cause the view of the data to be outdated. This configuration could be configurable, but if sync'ing from a pool of nodes and NOT lagging, you run the risk of missing logs.

**Comment by kluge** [comment]
Wouldn't a third solution be to not treat `result: []` as final until N blocks have gone by? That would require some additional polling, though. But could provide up-to-date state if the used node is up-to-date, albeit at the cost of additional calls.

Probably gets very tricky when you happen to get logs from a newer block, but not an older one. Lag is probably simpler and safer, but this would be a better experience for consistent Ethereum nodes without configuration.

**Comment by MicahZoltu** [comment]
I suspect that the engineering difficulty of having processing logic be conditional on empty array (and dealing with all of the sync issues around that) would be difficult.

We could perhaps have `ethereumjs-blockstream` (or a fork of it) have a background job that validates old blocks/logs, and if it finds that its data is inconsistent with its history it will rollback to that point and rebuild.  It sounds like this is a pretty common problem with Infura though, so this may result in a lot of thrashing.

**Comment by MicahZoltu** [comment]
We also could change the bandwidth profile of the AN<->EN connection and have blockstream (fork) fetch whole blocks rather than just the logs it needs.  This allows you to fetch a block by hash and notice when you get the wrong one, and it comes with all of the transaction receipts which can then be iterated over and you can fetch all of the logs from them.

**Comment by blacktemplar** [comment]
Isn't another idea remembering the last block which had a non-empty log (lets say block number N) and then use eth_getLogs({fromBlock: N, toBlock: "latest", filter: $setOfContractsFilter}) to get all logs up to the latest. With that method one cannot decide what the latest synced block is, one can only know the latest synced block with logs, but the user experience would be always up-to-date.

**Comment by joeykrug** [comment]
- How do AN + Blockstream handle reorgs at the moment?
- IMO this should be a period of time vs number of blocks to fix the propagation problem w/ infura
- "We could perhaps have ethereumjs-blockstream (or a fork of it) have a background job that validates old blocks/logs, and if it finds that its data is inconsistent with its history it will rollback to that point and rebuild." IMO this needs to be done too for validating the last n blocks, otherwise if you *do* get a reorg or propagation issue further back than the lag period [which *will* happen], it'll messup your logs/AN db.

**Comment by negamax** [comment]
@epheph can't this be resolved at Infura? For e.g. they can accept a session id of sorts from augur app and route all requests to one node for one app. If I understand this correctly, this issue will not happen if running a local node

**Comment by gabbello** [comment]
Can we get the default paths for " local augurnode sync data. " for all OS-es?

**Comment by tobutridaz** [comment]
This is probably related. I was probably not in sync and I saw markets that were already expired. I placed a trade order on the market and it went through on the blockchain. The money seemed to have been returned through the contract. https://etherscan.io/tx/0xea8dfeb0b3c393322004a91b63a46eea15356d9a6c72a419a78de943b8a0045d 

Obviously I have no positions in my profile.

**Comment by joeykrug** [comment]
@negamax it can happen with a local node too

**Comment by epheph** [comment]
@gabbello The solution will be to lag some configurable number of seconds, for propogation, and we will expose this in the library and likely in the UI (or only override when using infura? We're still considering our options).

**Comment by bthaile** [comment]
Is the linux directory stated in the README correct?

**Comment by zach-is-my-name** [comment]
@bthaile I got the .deb from the releases page (directed from Augur.net), dpkg'ed and ran.... where is the README?

**Comment by bthaile** [comment]
I should have said repo README. 
https://github.com/AugurProject/augur-app

**Comment by zach-is-my-name** [comment]
Yes it's correct thanks

**Comment by epheph** [comment]
Has anyone who was impacted by this issue, who is using infura, seen missing markets lately? We are currently intentionally lagging when not connected to localhost, to avoid missing data (allowing server-side propagation).

**Comment by joeykrug** [comment]
I haven't seen any

Btw have we implemented a full fix by doing this to make sure there's not a rollback / reorg further back than the lag?

> "We could perhaps have ethereumjs-blockstream (or a fork of it) have a background job that validates old blocks/logs, and if it finds that its data is inconsistent with its history it will rollback to that point and rebuild."

**Comment by joeykrug** [comment]
> Currently, we will not cancel out re-orgs that we see within that timeline

Which timeline does this refer to?

The rest sounds great!

**Comment by adrake33** [comment]
@epheph Can this issue be closed? Is there any reason to keep it open?
